'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace ClassLibrary1

	Partial Public Class XtraReport2
		Inherits SomeBaseReport

		Private Sub InitializeComponent()
			Dim reportInitializer As New DevExpress.XtraReports.ReportInitializer(Me, "ClassLibrary1.XtraReport2.vsrepx")

			' Controls
			Me.topMarginBand1 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.TopMarginBand)("topMarginBand1")
			Me.detailBand1 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.DetailBand)("detailBand1")
			Me.bottomMarginBand1 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.BottomMarginBand)("bottomMarginBand1")
			Me.label1 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.XRLabel)("label1")
		End Sub
		Private topMarginBand1 As DevExpress.XtraReports.UI.TopMarginBand
		Private detailBand1 As DevExpress.XtraReports.UI.DetailBand
		Private bottomMarginBand1 As DevExpress.XtraReports.UI.BottomMarginBand
		Private label1 As DevExpress.XtraReports.UI.XRLabel
	End Class
End Namespace
