'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace ClassLibrary1

	Partial Public Class XtraReport1
		Inherits DevExpress.XtraReports.UI.XtraReport

		Private Sub InitializeComponent()
			Dim reportInitializer As New DevExpress.XtraReports.ReportInitializer(Me, "ClassLibrary1.XtraReport1.vsrepx")

			' Controls
			Me.TopMargin = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.TopMarginBand)("TopMargin")
			Me.BottomMargin = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.BottomMarginBand)("BottomMargin")
			Me.Detail = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.DetailBand)("Detail")
			Me.label1 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.XRLabel)("label1")
		End Sub
		Private TopMargin As DevExpress.XtraReports.UI.TopMarginBand
		Private BottomMargin As DevExpress.XtraReports.UI.BottomMarginBand
		Private Detail As DevExpress.XtraReports.UI.DetailBand
		Private label1 As DevExpress.XtraReports.UI.XRLabel
	End Class
End Namespace
