'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace ClassLibrary1.NewFolder

	Partial Public Class XtraReport1
		Inherits DevExpress.XtraReports.UI.XtraReport

		Private Sub InitializeComponent()
			Dim reportInitializer As New DevExpress.XtraReports.ReportInitializer(Me, "ClassLibrary1.NewFolder.XtraReport1.vsrepx")

			' Controls
			Me.topMarginBand1 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.TopMarginBand)("topMarginBand1")
			Me.detailBand1 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.DetailBand)("detailBand1")
			Me.bottomMarginBand1 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.BottomMarginBand)("bottomMarginBand1")
			Me.pictureBox1 = reportInitializer.GetControl(Of DevExpress.XtraReports.UI.XRPictureBox)("pictureBox1")
		End Sub
		Private topMarginBand1 As DevExpress.XtraReports.UI.TopMarginBand
		Private detailBand1 As DevExpress.XtraReports.UI.DetailBand
		Private bottomMarginBand1 As DevExpress.XtraReports.UI.BottomMarginBand
		Private pictureBox1 As DevExpress.XtraReports.UI.XRPictureBox
	End Class
End Namespace
